
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-podgroupprediction
  failurePolicy: Fail
  name: prediction.crane.io_podgrouppredictions_webhook
  rules:
  - apiGroups:
    - prediction.crane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podgrouppredictions
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-podgroupprediction
  failurePolicy: Fail
  name: prediction.crane.io_podgrouppredictions_webhook
  rules:
  - apiGroups:
    - prediction.crane.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podgrouppredictions
  sideEffects: None
